import { type CategoryIcon } from '@domain';
import { addIcons } from 'ionicons';
import {
  addOutline,
  alertCircleOutline,
  archiveOutline,
  arrowUndoOutline,
  briefcaseOutline,
  cafeOutline,
  calendarOutline,
  cameraOutline,
  carOutline,
  cartOutline,
  checkmarkCircle,
  checkmarkOutline,
  chevronBackOutline,
  chevronDownOutline,
  chevronForwardOutline,
  cloudDownloadOutline,
  cloudUploadOutline,
  closeOutline,
  copyOutline,
  createOutline,
  documentTextOutline,
  ellipsisVertical,
  expandOutline,
  filmOutline,
  funnelOutline,
  giftOutline,
  homeOutline,
  imageOutline,
  imagesOutline,
  laptopOutline,
  lockClosedOutline,
  medkitOutline,
  pricetagOutline,
  pricetagsOutline,
  refreshOutline,
  reorderTwoOutline,
  restaurantOutline,
  searchOutline,
  settingsOutline,
  shareOutline,
  shirtOutline,
  squareOutline,
  trashOutline,
  warningOutline,
} from 'ionicons/icons';

/** Registers only the icons the app uses, so the bundle carries no unused SVG. */
export function registerIcons(): void {
  addIcons({
    addOutline,
    alertCircleOutline,
    archiveOutline,
    arrowUndoOutline,
    briefcaseOutline,
    cafeOutline,
    calendarOutline,
    cameraOutline,
    carOutline,
    cartOutline,
    checkmarkCircle,
    checkmarkOutline,
    chevronBackOutline,
    chevronDownOutline,
    chevronForwardOutline,
    cloudDownloadOutline,
    cloudUploadOutline,
    closeOutline,
    copyOutline,
    createOutline,
    documentTextOutline,
    ellipsisVertical,
    expandOutline,
    filmOutline,
    funnelOutline,
    giftOutline,
    homeOutline,
    imageOutline,
    imagesOutline,
    laptopOutline,
    lockClosedOutline,
    medkitOutline,
    pricetagOutline,
    pricetagsOutline,
    refreshOutline,
    reorderTwoOutline,
    restaurantOutline,
    searchOutline,
    settingsOutline,
    shareOutline,
    shirtOutline,
    squareOutline,
    trashOutline,
    warningOutline,
  });
}

export const CATEGORY_ICON_NAMES: Readonly<Record<CategoryIcon, string>> = {
  cart: 'cart-outline',
  restaurant: 'restaurant-outline',
  car: 'car-outline',
  medkit: 'medkit-outline',
  briefcase: 'briefcase-outline',
  cafe: 'cafe-outline',
  home: 'home-outline',
  film: 'film-outline',
  laptop: 'laptop-outline',
  gift: 'gift-outline',
  shirt: 'shirt-outline',
  pricetag: 'pricetag-outline',
};
